window.ColorData_cn = {
    "pale": "苍白",
    "fair": "白皙",
    "tan": "古铜",
    "olive": "橄榄",
    "dusky": "暗褐",
    "dark": "深色",
    "ebony": "乌木",
    "light red": "浅红",
    "red": "红",
    "dark red": "深红",
    "red orange": "橙红",
    "light orange": "浅橙",
    "orange": "橙",
    "yellow": "黄",
    "yellow-orange": "橙黄",
    "pale yellow": "淡黄",
    "yellow-green": "黄绿",
    "viridescent": "翠绿",
    "pale green": "浅绿",
    "green": "绿",
    "dark green": "深绿",
    "aqua": "水蓝",
    "teal": "青",
    "cerulean": "蔚蓝",
    "sky blue": "天蓝",
    "pale blue": "浅蓝",
    "blue": "蓝",
    "dark blue": "深蓝",
    "ultramarine": "群青",
    "indigo": "靛蓝",
    "light purple": "浅紫",
    "purple": "紫",
    "deep purple": "深紫",
    "lavender": "薰衣草",
    "brown": "棕",
    "black": "黑",
    "gray": "灰",
    "white": "白",
    "pink": "粉",
    "rose": "玫瑰",
    "peach": "蜜桃",
    "neon pink": "荧光粉",
    "mottled pink and black": "粉黑斑驳",
    "black and white": "黑白",
    "black and yellow": "黑黄",
    "copper": "铜",
    "bronze": "青铜",
    "silver": "银",
    "gold": "金",
    "platinum": "铂金",
    "brass": "黄铜",
    "cobalt": "钴蓝",
    "gunmetal": "枪灰",
    "steel": "钢",
    "sable": "貂黑",
    "iridescent": "虹彩",
    "candy red": "糖果红",
    "sunset gold": "日落金",
    "tangerine orange": "橘橙",
    "lemon yellow": "柠檬黄",
    "lime green": "青柠绿",
    "candy teal": "糖果青",
    "midnight blue": "午夜蓝",
    "electric purple": "电光紫",
    "candy pink": "糖果粉",
    "glowing red": "发光红",
    "glowing orange": "发光橙",
    "glowing yellow": "发光黄",
    "glowing green": "发光绿",
    "glowing blue": "发光蓝",
    "glowing purple": "发光紫",
    "glowing pink": "发光粉",
    "glowing gold": "发光金",
    "luminous cyan": "荧光青",
    "luminous violet": "荧光紫",
    "luminous silver": "荧光银",
    "hot white": "炽白",
    "glowing ember": "余烬",
    "fiery blue": "烈焰蓝",
    "crimson": "绯红",
    "garnet": "石榴石",
    "ruby": "红宝石",
    "citrine": "黄水晶",
    "topaz": "黄玉",
    "amber": "琥珀",
    "peridot": "橄榄石",
    "emerald": "祖母绿",
    "jade": "翡翠",
    "turquoise": "绿松石",
    "aquamarine": "海蓝宝",
    "lapis": "青金石",
    "sapphire": "蓝宝石",
    "violet": "紫罗兰",
    "amethyst": "紫水晶",
    "opal": "蛋白石",
    "pearl": "珍珠",
    "onyx": "玛瑙",
    "crystal": "水晶",
    "diamond": "钻石"
};
